### ISSUE TITLE
Application error: a server-side exception has occurred (see the server logs for more information).

### ISSUE THREAD

**Issue by Tamer7** [geeky-prashant/nextjs-ai-chatbot#1]
Seems the app is not accessible via the link

**Comment by geeky-prashant** [comment]
Hey Tamer7, the issue has been resolved and now you can access the app via https://nextjs-ai-chatbot-kappa.vercel.app/

![screencapture-nextjs-ai-chatbot-kappa-vercel-app-notes-2024-03-12-19_32_05](https://github.com/geeky-prashant/nextjs-ai-chatbot/assets/95212238/6681b8b5-6b6c-4815-a1df-2d5bfffcdbba)
